/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 12-Mar-2020 23:04:57
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 300
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include <arm_math.h>

/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define NUM_TAPS_Q15  300
const q15_t firCoeffsQ15_L[300] = {
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      0,      1,      1,      1,      1,      1,
        1,      1,      1,      1,      2,      2,      2,      2,      2,
        2,      2,      2,      3,      3,      3,      3,      3,      3,
        3,      3,      2,      2,      2,      2,      1,      1,      0,
        0,     -1,     -2,     -3,     -4,     -5,     -6,     -7,     -9,
      -10,    -12,    -13,    -15,    -17,    -19,    -21,    -23,    -25,
      -27,    -29,    -31,    -34,    -36,    -38,    -40,    -42,    -44,
      -45,    -47,    -48,    -49,    -50,    -51,    -51,    -51,    -51,
      -50,    -48,    -47,    -44,    -41,    -38,    -34,    -29,    -24,
      -18,    -11,     -4,      4,     13,     23,     33,     44,     56,
       68,     81,     95,    110,    125,    141,    158,    175,    193,
      211,    230,    249,    268,    288,    308,    328,    348,    368,
      389,    409,    429,    448,    468,    486,    505,    523,    540,
      556,    572,    587,    601,    614,    626,    638,    647,    656,
      664,    670,    675,    679,    682,    683,    683,    682,    679,
      675,    670,    664,    656,    647,    638,    626,    614,    601,
      587,    572,    556,    540,    523,    505,    486,    468,    448,
      429,    409,    389,    368,    348,    328,    308,    288,    268,
      249,    230,    211,    193,    175,    158,    141,    125,    110,
       95,     81,     68,     56,     44,     33,     23,     13,      4,
       -4,    -11,    -18,    -24,    -29,    -34,    -38,    -41,    -44,
      -47,    -48,    -50,    -51,    -51,    -51,    -51,    -50,    -49,
      -48,    -47,    -45,    -44,    -42,    -40,    -38,    -36,    -34,
      -31,    -29,    -27,    -25,    -23,    -21,    -19,    -17,    -15,
      -13,    -12,    -10,     -9,     -7,     -6,     -5,     -4,     -3,
       -2,     -1,      0,      0,      1,      1,      2,      2,      2,
        2,      3,      3,      3,      3,      3,      3,      3,      3,
        2,      2,      2,      2,      2,      2,      2,      2,      1,
        1,      1,      1,      1,      1,      1,      1,      1,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0
};
